on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Build macOS amd64
        env:
          CGO_ENABLED: 0
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -ldflags "-s -w -X ecwid-images-downloader/cmd.version=${{ github.event.release.tag_name }} -X ecwid-images-downloader/cmd.commit=${{ github.sha }} -X ecwid-images-downloader/cmd.date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -o ecwid-images-downloader-amd64
          tar -czvf ecwid-images-downloader-amd64.tar.gz ecwid-images-downloader-amd64
      - name: Build macOS arm64
        env:
          CGO_ENABLED: 0
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -ldflags "-s -w -X ecwid-images-downloader/cmd.version=${{ github.event.release.tag_name }} -X ecwid-images-downloader/cmd.commit=${{ github.sha }} -X ecwid-images-downloader/cmd.date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -o ecwid-images-downloader-arm64
          tar -czvf ecwid-images-downloader-arm64.tar.gz ecwid-images-downloader-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ecwid-images-downloader-arm64.tar.gz
            ecwid-images-downloader-amd64.tar.gz